stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t pet-project .
  only:
    - main

test:
  stage: test
  image: python:3.11
  script:
    - pip install ".[dev]"
    - pytest
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes"
    - kubectl apply -f k8s/
  only:
    - main
