apiVersion: v1
kind: ConfigMap
metadata:
  name: pet-project-config
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/petdb"
  REDIS_URL: "redis://redis-service:6379/0"
  REDIS_CACHE_TTL_SECONDS: "3600"
